    app:
        restart: always
        build: .
        ports:
            - "8080:80"
        volumes:
            - $PWD/app:/code/app
        depends_on:
            - redis
        environment:
            - PYTHONUNBUFFERED=1
